
Dimaip:
  TwitterHelper:
    oauthAccessToken: ''
    oauthAccessTokenSecret: ''
    consumerKey: ''
    consumerSecret: ''
Neos:
  Neos:
    typoScript:
      autoInclude:
        Dimaip.TwitterHelper: true
  Fusion:
    defaultContext:
      Twitter: Dimaip\TwitterHelper\Eel\TwitterHelper
